### ISSUE TITLE
Bug in the docker-compose.yml file.

### ISSUE THREAD

**Issue by viztastic** [MBuffenoir/elk#1]
Hi,

Is there a typo in the docker-compose file? The "volumes" tag at the very end seems to be an error. 

When I run the container on ubuntu, it seems to exit the elasticdata container with an error of 0.

**Comment by MBuffenoir** [comment]
Hi, from the documentation of the v2 format it seems to be the way to do it.
https://docs.docker.com/compose/compose-file/#volumes-volume-driver
Though it seems I could safely remove the ":" if I don't specify a path or a volume driver after.

**Comment by viztastic** [comment]
Hey @MBuffenoir you're right. It turns out the `chown` command was spitting out the error. When I comment the chown command it all seems to work fine.

Is there a reason why you are applying that command? 

(Thanks for the speedy response btw! Your tutorial was really helpful)

**Comment by MBuffenoir** [comment]
Yep, the elasticsearch needs special permission on its data to function properly.
